FROM node:22-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . ./
RUN npm run build
RUN npm prune --omit=dev

FROM node:22-alpine
WORKDIR /app

ENV NODE_ENV=production
ENV HTTP_PORT=8080
ENV SPAWN_NGINX=false
ENV ROUTING_PREFIX=/api

COPY --from=builder /app ./

EXPOSE 8080

CMD ["node", "src/server.js"]
