apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-app-config
  labels:
    app.kubernetes.io/component: runtime-config
data:
  NODE_ENV: "production"
  HTTP_PORT: "8080"
  SPAWN_NGINX: "false"
  ROUTING_PREFIX: "/api"
  SQL_DATABASE_HOST: "shared-mysql-haproxy.cars-operator-system.svc.cluster.local"
  SQL_DATABASE_PORT: "3306"
