apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-app
  labels:
    app.kubernetes.io/component: api
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-app
      app.kubernetes.io/component: api
